name: markettransport
favicon: null
layout_spectrum: 0.28307
typography_spectrum: 0.41432
title: Market Transport
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#0b090e'
    - '#ddd6cc'
    - '#6b6663'
    - '#b3a797'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
